# Generated by Django 4.0 on 2023-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_DRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drf', models.CharField(max_length=100)),
                ('email_drf', models.EmailField(max_length=250)),
            ],
        ),
    ]
